log_format terse '$status $request_method $request_uri';

server {
    listen 8080;
    root /usr/share/nginx/html;
    access_log /dev/stdout terse;

    location /api/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri /index.html;
    }
}
