"""add book added_by

Revision ID: 1977855561e5
Revises: d815fe10db6d
Create Date: 2026-09-30 14:26:46.909869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1977855561e5'
down_revision = 'd815fe10db6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_added_by_id_users'), 'users', ['added_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_added_by_id_users'), type_='foreignkey')
        batch_op.drop_column('added_by_id')

    # ### end Alembic commands ###
