"""add track logging

Revision ID: 390414d15b3e
Revises: abf4ff3365c5
Create Date: 2026-09-17 19:34:23.891796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390414d15b3e'
down_revision = 'abf4ff3365c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_position', sa.Integer(), nullable=False),
    sa.Column('to_position', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_progress_track_id_tracks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_track_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_progress'))
    )
    with op.batch_alter_table('track_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_progress_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_progress_track_id'))

    op.drop_table('track_progress')
    # ### end Alembic commands ###
