"""add rating

Revision ID: 55007945e945
Revises: 1977855561e5
Create Date: 2026-09-30 16:24:22.762041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55007945e945'
down_revision = '1977855561e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
