"""position mixin

Revision ID: 61e377e6b50c
Revises: dcd2a9c7b576
Create Date: 2026-10-03 14:54:55.381935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e377e6b50c'
down_revision = 'dcd2a9c7b576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('playlist_position', new_column_name='sort_order')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    op.execute("UPDATE playlists SET sort_order = id")

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('sort_order', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('sort_order', new_column_name='playlist_position')

    # ### end Alembic commands ###
