"""add track ordering

Revision ID: abf4ff3365c5
Revises: 2d6c5dcbca73
Create Date: 2026-09-17 18:45:23.977378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf4ff3365c5'
down_revision = '2d6c5dcbca73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_position', sa.Integer(), nullable=False, server_default='0'))

    # number each playlist's tracks 1..n in insertion order
    op.execute("""
        UPDATE tracks SET playlist_position = (
            SELECT COUNT(*) FROM tracks t2
            WHERE t2.playlist_id = tracks.playlist_id AND t2.id <= tracks.id
        )
    """)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('playlist_position', server_default=None) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('playlist_position')

    # ### end Alembic commands ###
