"""track add updated_at

Revision ID: bf4a1af7b33f
Revises: e91c85f1fe1e
Create Date: 2026-09-30 08:00:15.319364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4a1af7b33f'
down_revision = 'e91c85f1fe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE tracks SET updated_at = CURRENT_TIMESTAMP")

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('updated_at', nullable=False, server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
