"""rename last_read

Revision ID: e1e1f3177125
Revises: 61e377e6b50c
Create Date: 2026-10-03 15:46:23.918363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e1f3177125'
down_revision = '61e377e6b50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('position_updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_read_at')

    # ### end Alembic commands ###
