"""number_of_pages to pages

Revision ID: 8eede574d9fd
Revises: a1ca62d029f4
Create Date: 2026-08-29 13:54:24.604886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eede574d9fd'
down_revision = 'a1ca62d029f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('medium',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
