"""playlist cascade track

Revision ID: 9839f3ae722f
Revises: c1082a7d9b04
Create Date: 2026-09-04 04:20:47.367111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9839f3ae722f'
down_revision = 'c1082a7d9b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tracks_playlist_id_playlists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_playlist_id_playlists'), 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tracks_playlist_id_playlists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_playlist_id_playlists'), 'playlists', ['playlist_id'], ['id'])

    # ### end Alembic commands ###
