"""add fetch_status, track position/unit/total

Revision ID: a1ca62d029f4
Revises: 2d19c0c8eb1c
Create Date: 2026-08-25 20:28:14.174845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1ca62d029f4"
down_revision = "2d19c0c8eb1c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fetch_status",
                sa.Enum(
                    "not_attempted",
                    "unreachable",
                    "timeout",
                    "not_found",
                    "http_error",
                    "ok",
                    name="fetchstatus",
                    native_enum=False,
                    length=20,
                ),
                server_default="not_attempted",
                nullable=False,
            )
        )

    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("position", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(sa.Column("unit", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("total", sa.Integer(), nullable=True))
        batch_op.drop_column("current_page")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "current_page",
                sa.INTEGER(),
                server_default=sa.text("'1'"),
                nullable=False,
            )
        )
        batch_op.drop_column("total")
        batch_op.drop_column("unit")
        batch_op.drop_column("position")

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_column("fetch_status")

    # ### end Alembic commands ###
