"""initial schema

Revision ID: c1082a7d9b04
Revises: 
Create Date: 2026-09-01 18:39:07.487646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1082a7d9b04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('pages', sa.Integer(), server_default='1', nullable=False),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('fetch_status', sa.Enum('not_attempted', 'unreachable', 'timeout', 'not_found', 'http_error', 'invalid_format', 'ok', name='fetchstatus', native_enum=False, length=20), server_default='not_attempted', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('isbn', name=op.f('uq_books_isbn'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_book_authors_author_id_authors')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_authors_book_id_books')),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name=op.f('pk_book_authors'))
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_playlists_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('medium', sa.Enum('pdf', 'physical', 'audio', name='medium'), server_default='physical', nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_tracks_book_id_books')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_tracks_playlist_id_playlists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('playlists')
    op.drop_table('book_authors')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
