"""users expanded

Revision ID: c15805d04b78
Revises: 3643a2dbdf64
Create Date: 2026-08-13 23:20:03.608186

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c15805d04b78"
down_revision = "3643a2dbdf64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column("password_hash", sa.String(length=128), nullable=False))
        batch_op.drop_constraint(batch_op.f("uq_users_name"), type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_users_username"), ["username"])
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f("uq_users_username"), type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_users_name"), ["name"])
        batch_op.drop_column("password_hash")
        batch_op.drop_column("username")

    # ### end Alembic commands ###
